const express=require('express')
const router=express.Router()
const {createuser,loginAuthor}=require("../controller/userController")
const{createbook,getBooks,getBooksById,updatedetails,deletebook}=require("../controller/bookController")
const{createreview,updateReview,deleteReview}=require("../controller/reviewController")
const{authentication,authorisation}=require("../middleware/authentication")

router.post("/register",createuser)
router.post("/books",authentication,authorisation,createbook)
router.get("/books",authentication,authorisation,getBooks)
router.post("/books/:bookId/review",authentication,authorisation,createreview)
router.get("/books/:bookId",authentication,authorisation,getBooksById)
router.put("/books/:bookId",authentication,authorisation,updatedetails)
router.delete("/books/:bookId",authentication,authorisation,deletebook)
router.put("/books/:bookId/review/:reviewId",authentication,authorisation,updateReview)
router.delete("/books/:bookId/review/:reviewId",authentication,authorisation,deleteReview)
router.post('/login',loginAuthor)
module.exports=router